### ISSUE TITLE
How do you load the model after training?

### ISSUE THREAD

**Issue by atharvasj780** [gaga1313/Image-Captioning#1]

**Comment by gaga1313** [comment]
steps to load checkpoint model
1) Create New model with the same architecture. Just run the cells which create model architecture but this time don't train it. 
2) Create Checkpoint and Checkpoint_Manager. Execute the cells which create checkpoint and checkpoint manager
3) Do **checkpoint.restore('path to you checkpoint index file')** in my case i will be doing ckpt.restore(path) since i create 
    checkpoint object with name **ckpt** and that's it. The checkpoint will restore the weights into your new model instances.
4) Basically when you use checkpoint it creates a 'checkpoint file' , 'Index file' and 'data file' in the provided directory. for more 
    detailed information about these files visit 
    https://towardsdatascience.com/checkpointing-deep-learning-models-in-keras-a652570b8de6
